/**
 * This class is generated by jOOQ
 */
package org.jooq.util.maven.sample;


import javax.annotation.Generated;

import org.jooq.util.maven.sample.tables.Author;
import org.jooq.util.maven.sample.tables.Book;
import org.jooq.util.maven.sample.tables.BookStore;
import org.jooq.util.maven.sample.tables.BookToBookStore;
import org.jooq.util.maven.sample.tables.Databasechangeloglock;
import org.jooq.util.maven.sample.tables.Language;


/**
 * Convenience access to all tables in library
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table library.author
	 */
	public static final Author AUTHOR = org.jooq.util.maven.sample.tables.Author.AUTHOR;

	/**
	 * The table library.book
	 */
	public static final Book BOOK = org.jooq.util.maven.sample.tables.Book.BOOK;

	/**
	 * The table library.book_store
	 */
	public static final BookStore BOOK_STORE = org.jooq.util.maven.sample.tables.BookStore.BOOK_STORE;

	/**
	 * The table library.book_to_book_store
	 */
	public static final BookToBookStore BOOK_TO_BOOK_STORE = org.jooq.util.maven.sample.tables.BookToBookStore.BOOK_TO_BOOK_STORE;

	/**
	 * The table library.DATABASECHANGELOGLOCK
	 */
	public static final Databasechangeloglock DATABASECHANGELOGLOCK = org.jooq.util.maven.sample.tables.Databasechangeloglock.DATABASECHANGELOGLOCK;

	/**
	 * The table library.language
	 */
	public static final Language LANGUAGE = org.jooq.util.maven.sample.tables.Language.LANGUAGE;
}
