/**
 * This class is generated by jOOQ
 */
package org.jooq.util.maven.sample.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.util.maven.sample.Keys;
import org.jooq.util.maven.sample.Library;
import org.jooq.util.maven.sample.tables.records.DatabasechangeloglockRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Databasechangeloglock extends TableImpl<DatabasechangeloglockRecord> {

	private static final long serialVersionUID = -1369121304;

	/**
	 * The reference instance of <code>library.DATABASECHANGELOGLOCK</code>
	 */
	public static final Databasechangeloglock DATABASECHANGELOGLOCK = new Databasechangeloglock();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<DatabasechangeloglockRecord> getRecordType() {
		return DatabasechangeloglockRecord.class;
	}

	/**
	 * The column <code>library.DATABASECHANGELOGLOCK.ID</code>.
	 */
	public final TableField<DatabasechangeloglockRecord, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>library.DATABASECHANGELOGLOCK.LOCKED</code>.
	 */
	public final TableField<DatabasechangeloglockRecord, Boolean> LOCKED = createField("LOCKED", org.jooq.impl.SQLDataType.BIT.nullable(false), this, "");

	/**
	 * The column <code>library.DATABASECHANGELOGLOCK.LOCKGRANTED</code>.
	 */
	public final TableField<DatabasechangeloglockRecord, Timestamp> LOCKGRANTED = createField("LOCKGRANTED", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>library.DATABASECHANGELOGLOCK.LOCKEDBY</code>.
	 */
	public final TableField<DatabasechangeloglockRecord, String> LOCKEDBY = createField("LOCKEDBY", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * Create a <code>library.DATABASECHANGELOGLOCK</code> table reference
	 */
	public Databasechangeloglock() {
		this("DATABASECHANGELOGLOCK", null);
	}

	/**
	 * Create an aliased <code>library.DATABASECHANGELOGLOCK</code> table reference
	 */
	public Databasechangeloglock(String alias) {
		this(alias, DATABASECHANGELOGLOCK);
	}

	private Databasechangeloglock(String alias, Table<DatabasechangeloglockRecord> aliased) {
		this(alias, aliased, null);
	}

	private Databasechangeloglock(String alias, Table<DatabasechangeloglockRecord> aliased, Field<?>[] parameters) {
		super(alias, Library.LIBRARY, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<DatabasechangeloglockRecord> getPrimaryKey() {
		return Keys.KEY_DATABASECHANGELOGLOCK_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<DatabasechangeloglockRecord>> getKeys() {
		return Arrays.<UniqueKey<DatabasechangeloglockRecord>>asList(Keys.KEY_DATABASECHANGELOGLOCK_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Databasechangeloglock as(String alias) {
		return new Databasechangeloglock(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Databasechangeloglock rename(String name) {
		return new Databasechangeloglock(name, null);
	}
}
